#!/usr/bin/python

from subprocess import call
import os
import sys

def which(program):
    def is_exe(fpath):
        return os.path.isfile(fpath) and os.access(fpath, os.X_OK)

    fpath, fname = os.path.split(program)
    if fpath:
        if is_exe(program):
            return program
    else:
        for path in os.environ["PATH"].split(os.pathsep):
            path = path.strip('"')
            exe_file = os.path.join(path, program)
            if is_exe(exe_file):
                return exe_file

    return None

def run():
    current_directory = os.path.dirname(os.path.realpath(sys.argv[0]))
    data_path = os.path.join(current_directory, 'data')
    mongod = which('mongod')
    full_line = mongod + " --dbpath " + data_path + " --journal"

    if not mongod:
        print('mongod not found')
        return

    if not os.path.exists(data_path):
        os.makedirs(data_path)

    print('Calling mongod with "' + full_line + '"')

    call(full_line, shell=True)


run()
